export default {
  LOGIN_REQUEST : 'LOGIN_REQUEST',
  LOGIN_SUCCESS : 'LOGIN_SUCCESS',
  LOGIN_FAILURE : 'LOGIN_FAILURE',

  FETCH_USERS_REQUEST : 'FETCH_USERS_REQUEST',
  FETCH_USERS_SUCCESS : 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE : 'FETCH_USERS_FAILURE',

  UPDATE_USER_REQUEST : 'UPDATE_USER_REQUEST',
  UPDATE_USER_SUCCESS : 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILURE : 'UPDATE_USER_FAILURE',
  
}